### ISSUE TITLE
User를 통한 문제집 조회

### ISSUE THREAD

**Issue by TaeyeonRoyce** [dnd-side-project/dnd-7th-9-backend#35]
저희 도메인 구조가 현재 
User -> StudyGroup -> Goal -> Question 흐름으로 모두 1 : N 매핑이 되어 있습니다.
User로 Question을 모두 조회하는 경우, 저 플로우를 모두 타야한다는 문제점이 있습니다.
최대 $N^3$ 의 복잡도가 발생할 수 있을 것 같아요..
<br>
<br>
그래서 생각해본 방안은, 이미 존재하는 UserSolveQuestion같은 중간 테이블을 두는 것 입니다.
만약 이 방안을 하게 된다면 다음과 같은 동작이 추가될 것 같아요.
- 어떤 User(1L)가 QuestinoBook(1L)을 등록하면
- 해당 QuestionBook을 풀어야하는 모든 스터디원에 대해 UserSolveQuestion에 saveAll (`UserSolveQuestion`테이블에 풀이 완료 필드를 추가하여도 될 것 같습니다)

- saveAll(
    {User(2L), QuestionBook(1L)}, 
    {User(3L), QuestionBook(1L)},
    {User(4L), QuestionBook(1L)} 
) 이런 식으로요?

리뷰 부탁드려요!! 구현해보다가 너무 뎁스가 깊어져서 고민해보았습니다

**Comment by Sim-mi-gyeong** [comment]
맞아요 저희 워낙 타고 들어가는 매핑이 연속되어 있어서,, 중간에 매핑할 수 있게 하는 게 맞을 것 같아요! 그러면 엔티티 새로 하나 만드는거죠?!

**Comment by Sim-mi-gyeong** [comment]
앗 PR 내용으로 확인하였습니다!!
