### ISSUE TITLE
docs : Backend Architecture 수정

### ISSUE THREAD

**Issue by Sim-mi-gyeong** [dnd-side-project/dnd-7th-9-backend#4]
CI-CD 환경 구축 수정에 따른 아키텍처 변경 확인 부탁드립니다 :) 🙆🏻‍♀️
- 노션 2주차 제출 미션 페이지 / 피그마에 올려놨습니다 !-! 

![image](https://user-images.githubusercontent.com/80315847/180070425-bb6d5fbb-8f98-4593-9c34-67aaa625d12f.png)

**Comment by TaeyeonRoyce** [comment]
고생하셨습니다! 👏
